parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
overrides:
  - files:
      - "test/**/*.ts"
    rules:
      '@typescript-eslint/no-explicit-any': 0
env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
