[workspace]
members = [
    "programs/cryptid_anchor",
    "programs/middleware/check_recipient",
    "programs/middleware/check_pass",
    "programs/middleware/time_delay"
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cryptid_anchor = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
check_recipient = "midcHDoZsxvMmNtUr8howe8MWFrJeHHPbAyJF1nHvyf"
check_pass = "midpT1DeQGnKUjmGbEtUMyugXL5oEBeXU3myBMntkKo"
time_delay = "midttN2h6G2CBvt1kpnwUsFXM6Gv7gratVwuo2XhSNk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "didso1Dpqpm4CsiCjzP766BGY89CAdD6ZBL68cRhFPc"
program = "tests/fixtures/sol_did_2.0.0.so"

[[test.genesis]]
address = "gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"
program = "tests/fixtures/solana_gateway_program.so"

[[test.validator.account]]
address = "78CJ7rLRbMg1eLKudJqmQp1wzPu1NEo9qRJhMXQKoNe7"
filename = "../fixtures/did-sol-idl-account.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
